# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'TIL to Code' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  

  # Pods  for TIL to Code
   pod "Firebase"
   pod "Firebase/Auth"
   pod "Firebase/Database"
end

  target 'TIL to CodeTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Firebase"
    pod "Firebase/Auth"
    pod "Firebase/Database"
  end

  target 'TIL to CodeUITests' do
    inherit! :search_paths
    # Pods for testing
    pod "Firebase"
    pod "Firebase/Auth"
    pod "Firebase/Database"
  end


